[package]
name = "word-members"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.22"
env_logger = "0.11.3" 
dotenv = "0.15.0"
mongodb = "3.0.1"
futures-util = "0.3"
