###
POST http://localhost:8080/word/create
Content-Type: application/json

{
    "name": "Phone",
    "members": ["Message","Call","Camera"]
}

###
GET http://localhost:8080/word/get
Content-Type: application/json